src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\Table;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

#[Entity(repositoryClass: UserRepository::class)]
#[Table(name: 'system_user')]
#[UniqueEntity(fields: 'identifier', message: 'This identifier is already in use')]
class User implements UserInterface
{
    final public const array ROLES
        = [
            'user' => 'ROLE_USER',
            'admin' => 'ROLE_ADMIN',
        ];

    #[Column, Id, GeneratedValue(strategy: 'SEQUENCE')]
    private ?int $id = 0;

    #[Column(unique: true), NotBlank]
    private string $identifier = '*';

    /**
     * @var array<string>
     */
    #[Column(type: Types::JSON)]
    private array $roles = [];

    /**
     * @var array<string>|null
     */
    #[Column(type: Types::JSON, nullable: true)]
    private ?array $params = [];

    #[Column(length: 100, nullable: true)]
    private ?string $googleId = null;

    #[Column(nullable: true)]
    private ?int $gitHubId = null;

    #[Column(nullable: true)]
    private ?int $gitLabId = null;

    /**
     * @return array{
     *     id: int|null,
     *     identifier: string|null
     * }
     */
    public function __serialize(): array
    {
        return [
            'id' => $this->id,
            'identifier' => $this->identifier,
        ];
    }

    /**
     * @param array{
     *     id: int|null,
     *     identifier: string|null
     * } $data
     */
    public function __unserialize(array $data): void
    {
        $this->id = $data['id'] ?? null;
        $this->identifier = (string) ($data['identifier'] ?? null);
    }

    #[\Override]
    public function eraseCredentials(): void
    {
    }

    #[\Override]
    public function getRoles(): array
    {
        $roles = $this->roles;

        // guarantee every user at least has ROLE_USER
        $roles[] = self::ROLES['user'];

        return \array_unique($roles);
    }

    /**
     * @param array<string> $roles
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return array<string>|null
     */
    public function getParams(): ?array
    {
        return $this->params;
    }

    public function getParam(string $name): string
    {
        return $this->params && \array_key_exists($name, $this->params)
            ? $this->params[$name]
            : '';
    }

    /**
     * @param array<string> $params
     */
    public function setParams(array $params): self
    {
        $this->params = $params;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    #[\Override]
    public function getUserIdentifier(): string
    {
        return $this->identifier;
    }

    public function setIdentifier(string $identifier): self
    {
        $this->identifier = $identifier;

        return $this;
    }

    /**
     * @todo this method is required by the the rememberMe functionality :(
     */
    public function getPassword(): ?string
    {
        return null;
    }

    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(?string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }

    public function getGitHubId(): ?int
    {
        return $this->gitHubId;
    }

    public function setGitHubId(?int $gitHubId): self
    {
        $this->gitHubId = $gitHubId;

        return $this;
    }

    public function getGitLabId(): ?int
    {
        return $this->gitLabId;
    }

    public function setGitLabId(?int $gitLabId): self
    {
        $this->gitLabId = $gitLabId;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/', name: 'app_default', methods: ['GET'])]
class DefaultController extends BaseController
{
    public function __invoke(
        #[Autowire('%kernel.project_dir%')] string $projectDir,
    ): Response {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'php_version' => PHP_VERSION,
            'symfony_version' => Kernel::VERSION,
            'project_dir' => $projectDir,
        ]);
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="module">
        import '{{ asset('lib/bootstrap_test.js') }}';
    </script>
{% endblock %}

{% block body %}
    <h2 class="mt-5">Symfony Playground Two <span class="bg-logo"></span></h2>

    {% if app.user %}
        <div class="alert alert-success">
            <h4>Welcome {{ app.user.param('user_name') ?: app.user.userIdentifier }}!</h4>
            {% if not app.user.param('user_name') %}
                Please <a href="{{ path('app_profile') }}">update your Profile</a>!
            {% endif %}
        </div>
    {% else %}
        <h4>
            Use the <code>symfony console user-admin</code> command to create a user so you can
            <a href="{{ path('login') }}">log in</a>!
        </h4>
    {% endif %}

    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Holy guacamole!</strong> You should check in on some of those fields below.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    <h4>
        We are using Symfony <code>{{ symfony_version }}</code> in <code>{{ app.environment }}</code> mode on
        PHP <code>{{ php_version }}</code>.
    </h4>

    <p class="lead">
        This friendly message is coming from your <b>{{ controller_name }}</b> at:
    </p>

    <ul>
        <li>
            Your Project at <code>{{ project_dir }}</code>
        </li>
        <li>
            Your Controller at
            <a href="{{ (project_dir ~ '/src/Controller/DefaultController.php')|file_link(0) }}">
                src/Controller/DefaultController.php
            </a>
        </li>
        <li>
            Your template at
            <a href="{{ (project_dir ~ '/templates/default/index.html.twig')|file_link(0) }}">
                templates/default/index.html.twig
            </a>
        </li>
        <li>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Launch demo modal
            </button>
            <button type="button" class="btn btn-primary" id="liveToastBtn">
                Show live toast
            </button>
        </li>
        <li>
            <p class="muted">Placeholder text to demonstrate some <a href="#" data-bs-toggle="tooltip"
                                                                     data-bs-title="Default tooltip">inline
                    links</a> with tooltips. This is now just filler, no killer. Content placed here just to
                mimic the presence of <a href="#" data-bs-toggle="tooltip" data-bs-title="Another tooltip">real
                    text</a>. And all that just to give you an idea of how tooltips would look when used in
                real-world situations. So hopefully you've now seen how <a href="#" data-bs-toggle="tooltip"
                                                                           data-bs-title="Another one here too">these
                    tooltips on links</a> can work in practice, once you use them on <a href="#"
                                                                                        data-bs-toggle="tooltip"
                                                                                        data-bs-title="The last tip!">your
                    own</a> site or project.</p>
        </li>
        <li>
            <button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover"
                    data-bs-title="Popover title"
                    data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to
                toggle popover
            </button>
        </li>
    </ul>

    <div class="alert alert-success" role="alert" {{ stimulus_controller('hello') }}>
        Stimulus test...
    </div>

    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Accordion Item #1
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>This is the first item's accordion body.</strong> It is shown by default, until the
                    collapse plugin adds the appropriate classes that we use to style each element. These
                    classes control the overall appearance, as well as the showing and hiding via CSS
                    transitions. You can modify any of this with custom CSS or overriding our default variables.
                    It's also worth noting that just about any HTML can go within the
                    <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Accordion Item #2
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>This is the second item's accordion body.</strong> It is hidden by default, until
                    the collapse plugin adds the appropriate classes that we use to style each element. These
                    classes control the overall appearance, as well as the showing and hiding via CSS
                    transitions. You can modify any of this with custom CSS or overriding our default variables.
                    It's also worth noting that just about any HTML can go within the
                    <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Accordion Item #3
                </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>This is the third item's accordion body.</strong> It is hidden by default, until the
                    collapse plugin adds the appropriate classes that we use to style each element. These
                    classes control the overall appearance, as well as the showing and hiding via CSS
                    transitions. You can modify any of this with custom CSS or overriding our default variables.
                    It's also worth noting that just about any HTML can go within the
                    <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
            </div>
        </div>
    </div>

    <p class="d-flex justify-content-center">
        <a href="http://www.wtfpl.net/">
            <img src="{{ asset('images/wtfpl-logo.png') }}" alt="WTFPL Logo">
        </a>
    </p>




    <!-- Toast -->
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <strong class="me-auto">Bootstrap</strong>
                <small>11 mins ago</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                Hello, world! This is a toast message.
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() }} - User Profile{% endblock %}

{% block body %}
    <h1>User Profile</h1>

    <p>Identifier: <code>{{ app.user.userIdentifier }}</code></p>

    {{ form_start(form) }}

    {{ form_widget(form) }}

    <button type="submit" class="btn btn-lg btn-outline-success" title="Save">
        <span class="bi-check"></span>
    </button>

    {{ form_end(form) }}

{% endblock %}